# =-=-=-=-=-=-=-=-= SERVICES =-=-=-=-=-=-=-=-=
services:
  # ========= POSTGRES DB =========
  postgres-db:
    image: postgres:17-alpine3.22

    container_name: sp-postgres

    env_file:
      - "./.env"

    environment:
      # in .env file in root catalog
      # "POSTGRES_PASSWORD"
      # "POSTGRES_USER"
      "DB_HOST": "postgres-db"
      "DB_PORT": "5432"
      "POSTGRES_DB": "servicepulse"

    ports:
      - "5432:5432"

    networks:
      - backend-network

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: always

  # ========= REDIS QUEUE =========
  redis-queue:
    image: redis:8.8-alpine

    container_name: sp-redis

    networks:
      - backend-network

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    restart: always

  # ========= BACKEND =========
  service-backend:
    image: sp-backend
    container_name: sp-backend-container

    build:
      context: ./backend
      dockerfile: Dockerfile

    networks:
      - backend-network
      - frontend-network

    environment:
      # in .env file in root catalog
      # "POSTGRES_PASSWORD"
      # "POSTGRES_USER"
      "DB_HOST": "postgres-db"
      "DB_PORT": "5432"
      "POSTGRES_DB": "servicepulse"

    env_file:
      - "./.env"

    ports:
      - "13000:13000"

    depends_on:
      - postgres-db

    restart: always

    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: "256M"

  # ========= FRONTEND =========
  frontend-service:
    image: sp-frontend
    container_name: sp-frontend-container

    build:
      context: ./frontend
      dockerfile: Dockerfile

    ports:
      - "5173:8080"

    networks:
      - frontend-network

    depends_on:
      - service-backend

    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "256M"

    restart: always



# =-=-=-=-=-=-=-=-= NETWORKS =-=-=-=-=-=-=-=-=
networks:
  frontend-network:
    name: sp-frontend-network
    driver: bridge
  backend-network:
    name: sp-backend-network
    driver: bridge

# =-=-=-=-=-=-=-=-= VOLUMES =-=-=-=-=-=-=-=-=
volumes:
  postgres_data:
  redis_data: